name: Build v3.13.1

on:
  workflow_dispatch:

permissions:
  contents: write

jobs:
  build-appimage:
    uses: ./.github/workflows/build-appimage.yml

  build-macos:
    uses: ./.github/workflows/build-macos.yml
    secrets: inherit

  build-windows:
    uses: ./.github/workflows/build-windows.yml
    secrets: inherit

  release:
    needs: [build-appimage, build-macos, build-windows]
    uses: ./.github/workflows/release.yml
    secrets: inherit
